    PROGRAM TIME
    REAL LTYR, LTMIN, DIST, ELAPSE
    INTEGER MINUTE, SECOND
C
C LTYR :DISTANCE TRAVELLED BY LIGHT IN ONE YEAR IN KM
C LTMIN :DISTANCE TRAVELLED BY LIGHT IN ONE MINUTE IN KM
C DIST :DISTANCE FROM SUN TO EARTH IN KM
C ELAPSE:TIME TAKEN TO TRAVEL A DISTANCE DIST IN MINUTES
C MINUTE:INTEGER NUMBER PART OF ELAPSE
C SECOND:INTEGER NUMBER OF SECONDS EQUIVALENT TO
C FRACTIONAL PART OF ELAPSE
C
    LTYR=9.46*10**12
    LTMIN=LTYR/(365.25*24.0*60.0)
    DIST=150.0*10**6
C
    ELAPSE=DIST/LTMIN
    MINUTE=ELAPSE
    SECOND=(ELAPSE-MINUTE)*60
C
    PRINT *,’ LIGHT TAKES ’,MINUTE,’ MINUTES’
    PRINT *,’ ’,SECOND,’ SECONDS’
    PRINT *,’ TO REACH THE EARTH FROM THE SUN’
    END PROGRAM TIME
